import PlanarHom.Basic
import PlanarHom.RankOne
import PlanarHom.Tensor
import PlanarHom.Boolean
import PlanarHom.Moments
import PlanarHom.Quotient
import PlanarHom.TensorPower
import PlanarHom.WeightRigidity
import PlanarHom.Gadgets
import PlanarHom.TractableEvaluation
import PlanarHom.Structures
import PlanarHom.PowerSumRigidity
import PlanarHom.ExponentialZeros
import PlanarHom.SampleSeparation
import PlanarHom.Normalization
import PlanarHom.PositivePowers
import PlanarHom.CubeAffine
import PlanarHom.BooleanMatrix
import PlanarHom.ZeroWeights
import PlanarHom.RelationApproximation
import PlanarHom.Interpolation
import PlanarHom.FixedChartClosedness
import PlanarHom.EntropyCompletion
import PlanarHom.Complexity
import PlanarHom.TracePositivity
import PlanarHom.TraceExponential
import PlanarHom.ExponentialDual
import PlanarHom.DistanceEmbedding
import PlanarHom.MachineComposition
import PlanarHom.AnalyticInverse
import PlanarHom.ExponentialGradient
import PlanarHom.KernelContinuation
import PlanarHom.CartesianGeometry

import PlanarHom.BinaryAdditionMachine

import PlanarHom.BinaryMultiplicationMachine
import PlanarHom.OracleSubstitution

import PlanarHom.LogarithmicSupport

import PlanarHom.MatrixExponentialDistance

import PlanarHom.WheatstoneCoefficients

import PlanarHom.OracleReductionComposition

import PlanarHom.BinarySubtractionMachine
import PlanarHom.OracleReductionLaws

import PlanarHom.DistanceKernelLog
import PlanarHom.WheatstoneLog
import PlanarHom.FrameMachines
import PlanarHom.ListCodecMachines

import PlanarHom.BinaryDivisionMachine
import PlanarHom.WheatstoneSupport

import PlanarHom.MaximumSupportLocalGeometry

import PlanarHom.DistanceKernelMaximality
import PlanarHom.MatrixExponentialRelations
import PlanarHom.PositiveExponentialEntries
import PlanarHom.GraphParallelMachines

import PlanarHom.CubeDirections
import PlanarHom.GraphParallelSemantics
import PlanarHom.BinaryGcdMachine

import PlanarHom.CubeCommutators
import PlanarHom.SymmetricBCHSector
import PlanarHom.PlanarGraphCode
import PlanarHom.PlanarFaces
import PlanarHom.GraphRealization

import PlanarHom.CubeBCHRigidity
import PlanarHom.CubeTensorExponential
import PlanarHom.PlanarStretch

import PlanarHom.CubeGraphMetric
import PlanarHom.RationalNormalizationMachine

import PlanarHom.UniformCubeKernelLog
import PlanarHom.CubeTensorCanonical
import PlanarHom.SchurPerturbation
import PlanarHom.MixedParallelMachines
import PlanarHom.MixedParallelSemantics

import PlanarHom.PartitionOutputBounds
import PlanarHom.RationalMultiplicationMachine
import PlanarHom.MarkedOccurrenceCount
import PlanarHom.SandwichSquareRigidity

import PlanarHom.FieldCoordinateHeights
import PlanarHom.CubeRationalKernelRigidity
import PlanarHom.GraphStretchCode

import PlanarHom.RawPartitionOutputBounds
import PlanarHom.FieldExpressionHeights
import PlanarHom.ReplicationPlanarity

import PlanarHom.SignedIntegerAdditionMachine
import PlanarHom.CubeNonnegativeFactors

import PlanarHom.RationalCircuits
import PlanarHom.LagrangeCoefficientHeights

import PlanarHom.FixedFieldArithmeticMachines
import PlanarHom.LagrangeDenominatorHeights
import PlanarHom.FixedAlgebraicField
import PlanarHom.CubeReindexTransport

import PlanarHom.LagrangeRecovery
import PlanarHom.BoundedIterationMachine
import PlanarHom.UnaryMarkedCount
import PlanarHom.BooleanLogPositivity
import PlanarHom.BooleanPDNormalization

import PlanarHom.MixedInterpolationRecovery
import PlanarHom.NatCanonicalizationMachine
import PlanarHom.ListMapMachines

import PlanarHom.RawGraphTransformMachines

import PlanarHom.PrescribedDomainTyping
import PlanarHom.MixedUnaryParallelMachines
import PlanarHom.UnaryOccurrenceCount
import PlanarHom.FixedPowerMachines
import PlanarHom.ListFlattenMachines
import PlanarHom.ListFilterMachines

import PlanarHom.SelectedProductClassSemantics
import PlanarHom.CoefficientListHeights
import PlanarHom.ListDedupMachines
import PlanarHom.PlanarPolygonalization

import PlanarHom.CanonicalCoordinateHeights
import PlanarHom.ExponentProductTableMachines
import PlanarHom.OracleListBatch
import PlanarHom.LinearFactorCoefficientMachines

import PlanarHom.MaterializedFieldHeights

import PlanarHom.PlanarRibbonExistence
import PlanarHom.ComputedMixedInterpolation
import PlanarHom.RepresentativeWordCertificates
import PlanarHom.MaterializedFieldListMachines

import PlanarHom.PreparedRecoveryCorrectness
import PlanarHom.FiniteReachableAlphabetMachines
import PlanarHom.PositiveUnaryPowerField
import PlanarHom.MixedEvaluationFieldMap

import PlanarHom.DomainProductInterpolationReductions
import PlanarHom.MixedLabelAliasReductions
import PlanarHom.FieldPresentationReductions
import PlanarHom.PositiveUnaryPowerOverfield
import PlanarHom.AlgebraicMixedLanguage

import PlanarHom.FiniteLanguageJointReductions
import PlanarHom.PositiveUnaryPowerJointAvailability

import PlanarHom.AlgebraicProductInterpolation

import PlanarHom.AlgebraicFiniteProductInterpolation
import PlanarHom.SupportTransformCompatibility

import PlanarHom.Corollary32Realization
import PlanarHom.PlanarGadgetInsertion

import PlanarHom.SpectralRealAvailability
import PlanarHom.PrescribedDomainStretch
import PlanarHom.GlobalDomainSpectralAvailability

import PlanarHom.UniformFixedFieldTransfer

import PlanarHom.ClosedFamilyLocalGeometry
import PlanarHom.DistanceKernelRealAvailability

import PlanarHom.DomainDistanceKernelRealAvailability

import PlanarHom.RationalParameterEffectiveTransfer
import PlanarHom.FinishedDependentMatrixFamilyReduction
import PlanarHom.TraceFieldDescent
import PlanarHom.ClosedFamilyCartesian

import PlanarHom.ClosedFamilyTensor

import PlanarHom.RootedRealAvailability
import PlanarHom.SupportComponentReduction

import PlanarHom.RootedRealTractability

import PlanarHom.PositiveWeightRealAvailability
import PlanarHom.WeightedRationalClosure

import PlanarHom.PositiveWeightSourceAvailability
import PlanarHom.FiniteWeightPowerRealAvailability

import PlanarHom.ActualTwinRealAvailability
import PlanarHom.ActualTwinZeroMatrix
import PlanarHom.RankOneEvaluationMachine

import PlanarHom.RankOneRealTractability
import PlanarHom.RelativeTraceComputation
import PlanarHom.FullLogarithmicPottsReduction
import PlanarHom.DomainFullLogarithmicAvailability
import PlanarHom.SharpPBridge

import PlanarHom.SingleTapeSharpPBridge
import PlanarHom.PottsTutteReduction
import PlanarHom.BooleanRatioIndependence
import PlanarHom.DomainEndpointLoopAvailability
import PlanarHom.BooleanFamilyPosDef

import PlanarHom.BooleanExceptionalSource
import PlanarHom.IsingLoopRemoval
import PlanarHom.FisherCubicWeighted
import PlanarHom.BooleanParameterRealAvailability

import PlanarHom.BooleanEffectiveLengthSamples
import PlanarHom.BooleanFieldTowerInverseMachines
import PlanarHom.GroupedShiftedInterpolation
import PlanarHom.BooleanRetainedTensor
import PlanarHom.FisherExpansionCorrespondence
import PlanarHom.RationalPowerRootMachines

import PlanarHom.BooleanGroupedRecoveryBounds
import PlanarHom.BooleanFieldTowerPolynomialMachines
import PlanarHom.BooleanGroupedTableCorrectness
import PlanarHom.MaterializedPolynomialInterpolationMachines
import PlanarHom.DomainParameterizedPowerReduction
import PlanarHom.FisherMatchingBoundary
import PlanarHom.FixedFieldOddPowerRootMachines
import PlanarHom.BooleanTensorPartitionMoments
import PlanarHom.BooleanSampledMetadataCertificates

import PlanarHom.PositiveFieldPowerRootMachines

-- Verified recovery/new implementation integration; see SOURCE_PROVENANCE.json.
import PlanarHom.AlgebraicLanguageExtensions
import PlanarHom.AlgebraicLanguagePresentation
import PlanarHom.ContextualMatrixAvailability
import PlanarHom.HeterogeneousGraphReduction
import PlanarHom.MixedColorEquivalence
import PlanarHom.MixedColorProblemEquivalence
import PlanarHom.PromisedFPClosureRegressions
import PlanarHom.PromisedFPReductionClosure
import PlanarHom.RectangularNormNormalization
import PlanarHom.RectangularNormalizationRegressions
import PlanarHom.RectangularTwinQuotient
import PlanarHom.RectangularWeightedNormNormalization
import PlanarHom.TypedBipartiteContext
import PlanarHom.TypedBipartiteSpectral
import PlanarHom.TypedBipartiteSpectralAvailability
import PlanarHom.TypedBipartiteSpectralAxiomAudit
import PlanarHom.TypedBipartiteSpectralBlocks
import PlanarHom.TypedBipartiteSpectralColorTransport
import PlanarHom.TypedBipartiteSpectralCompletion
import PlanarHom.TypedBipartiteSpectralEffective
import PlanarHom.TypedBipartiteSpectralEffectiveAvailability
import PlanarHom.TypedBipartiteSpectralEffectiveCompletion
import PlanarHom.TypedBipartiteSpectralEffectiveRegressions
import PlanarHom.TypedBipartiteSpectralFiniteBlocks
import PlanarHom.TypedBipartiteSpectralPaths
import PlanarHom.TypedBipartiteSpectralReduction
import PlanarHom.TypedBipartiteSpectralRegressions
import PlanarHom.TypedBipartiteSpectralSampling
import PlanarHom.TypedBipartiteSpectralTransport
import PlanarHom.TypedBipartiteSpectralUniform
import PlanarHom.TypedBipartiteSpectralUniformCompiler
import PlanarHom.TypedContextualMatrixAvailability
import PlanarHom.TypedContextualSpectralAxiomAudit
import PlanarHom.TypedContextualSpectralBlocks
import PlanarHom.TypedContextualSpectralClosure
import PlanarHom.TypedContextualSpectralEffective
import PlanarHom.TypedContextualSpectralRational
import PlanarHom.TypedContextualSpectralRegressions
import PlanarHom.TypedRealLanguagePresentation
import PlanarHom.BipartiteFullTwinFinite
import PlanarHom.BipartiteFullTwinSideEquiv
import PlanarHom.FiniteFieldQuotientLanguage
import PlanarHom.RectangularBipartiteBlock
import PlanarHom.ReimplementedFiniteTwins.FiniteBridge
import PlanarHom.ReimplementedFiniteTwins.QuotientReindex

-- Resumed integration: already independently verified typed transport and norm-source programs.
import PlanarHom.EndpointUnarySource
import PlanarHom.FixedSquareNormPowers
import PlanarHom.FixedSquareNormSource
import PlanarHom.NormalizationSquareSourceRegressions
import PlanarHom.NormalizedMomentProgramRegressions
import PlanarHom.PrescribedDomainColorTransport
import PlanarHom.PrescribedDomainReindexReduction
import PlanarHom.RectangularNormalizedMomentPrograms
import PlanarHom.RectangularSquareNormSource
import PlanarHom.TypedContextualCoordinateTransport
import PlanarHom.TypedCoordinateTransportAxiomAudit
import PlanarHom.TypedCoordinateTransportRegressions
import PlanarHom.TypedSideSwap
import PlanarHom.VertexMomentUnarySource
import PlanarHom.UnitBackgroundLanguage
import PlanarHom.ContextualGadgetClosure
import PlanarHom.RectangularNormalizationMomentSource
import PlanarHom.UnitBackgroundLanguageRegressions

-- Genuine weighted chart plus complete unchanged original source consumers.
import PlanarHom.CommonWeightedAmplitudeCoordinates
import PlanarHom.WeightedAmplitudeChartRegressions
import PlanarHom.RectangularBackgroundWeightedReconstruction
import PlanarHom.RectangularSideMomentPresentation
import PlanarHom.RectangularUnitCoreSource

-- Verified reconstructed Pfaffian algebra/runtime and finite-table geometry.
import PlanarHom.FktGeometryAxiomAudit
import PlanarHom.FktGeometryRegressions
import PlanarHom.OccurrenceKasteleynDual
import PlanarHom.OccurrenceKasteleynOrientationLog
import PlanarHom.OccurrenceKasteleynPeeling
import PlanarHom.OccurrenceKasteleynPeelingSemantics
import PlanarHom.OccurrenceKasteleynPolygonalCollars
import PlanarHom.OccurrenceKasteleynRecenteredCollars
import PlanarHom.OccurrenceOrientationLogMachines
import PlanarHom.OccurrencePfaffianCoreAxiomAudit
import PlanarHom.OccurrencePfaffianCoreRegressions
import PlanarHom.OccurrencePfaffianEliminationAlgorithm
import PlanarHom.OccurrencePfaffianEvaluationMachines
import PlanarHom.OccurrencePfaffianEvaluationProgram
import PlanarHom.OccurrencePfaffianExpansion
import PlanarHom.OccurrencePfaffianExpansionSigns
import PlanarHom.OccurrencePfaffianFisher
import PlanarHom.OccurrencePfaffianGridNormalization
import PlanarHom.OccurrencePfaffianIterationBounds
import PlanarHom.OccurrencePfaffianIterationInvariant
import PlanarHom.OccurrencePfaffianListPrimitives
import PlanarHom.OccurrencePfaffianListStep
import PlanarHom.OccurrencePfaffianMatrix
import PlanarHom.OccurrencePfaffianPairExchange
import PlanarHom.OccurrencePfaffianPairings
import PlanarHom.OccurrencePfaffianProgramBridge
import PlanarHom.OccurrencePfaffianRegressions
import PlanarHom.OccurrencePfaffianShear
import PlanarHom.OccurrencePfaffianShearAxiomAudit
import PlanarHom.OccurrencePfaffianShearRegressions
import PlanarHom.OccurrencePfaffianStateBounds
import PlanarHom.OccurrencePfaffianVertexLinearity
import PlanarHom.OccurrenceSkewCodeSemantics
import PlanarHom.PfaffianEliminationHeights
import PlanarHom.PfaffianEliminationTrace
import PlanarHom.PfaffianMachineAxiomAudit
import PlanarHom.PfaffianMachineRegressions
import PlanarHom.PfaffianMinorHeights
import PlanarHom.PfaffianPivotSemantics
import PlanarHom.PfaffianPivotSemanticsRegressions
import PlanarHom.PfaffianPivotShear
import PlanarHom.PfaffianSchurComplement
import PlanarHom.PfaffianSchurMinors
import PlanarHom.RadialPottsAssemblyRibbonMiddle

-- Genuine source coordinates, finite contextual access and connected orientation.
import PlanarHom.CoreSourceCoordinateAxiomAudit
import PlanarHom.CoreSourceCoordinateRegressions
import PlanarHom.FiniteJointSourceAvailability
import PlanarHom.HomogeneousSourceOrientationAxiomAudit
import PlanarHom.HomogeneousSourceOrientationConnected
import PlanarHom.HomogeneousSourceOrientationMachines
import PlanarHom.HomogeneousSourceOrientationRegressions
import PlanarHom.HomogeneousSourceOrientationSemantics
import PlanarHom.SubtypeColorEvaluation
import PlanarHom.TypedSideSourceAccess
import PlanarHom.TypedSideSourceAccessFamily
import PlanarHom.TypedSourceSideCoordinates
import PlanarHom.TypedYFamilyTransport
import PlanarHom.TypedYSourceAccess

-- Actual unconditional raw-table orientation runtime.
import PlanarHom.FktIterationRegressions
import PlanarHom.OccurrenceKasteleynOrientationIteration
import PlanarHom.OccurrenceKasteleynOrientationRuntimeBounds
import PlanarHom.OccurrenceKasteleynOrientationStepMachines
import PlanarHom.OccurrenceKasteleynPeelingMachines
import PlanarHom.OccurrenceKasteleynPivotMachines
import PlanarHom.OccurrenceKasteleynTablePrimitives
import PlanarHom.OrientationRuntimeAxiomAudit
import PlanarHom.OrientationRuntimeRegressions

-- Complete disconnected homogeneous source orientation and actual X/Y source access.
import PlanarHom.HomogeneousSourceOrientationComponents
import PlanarHom.HomogeneousSourceOrientationCrossing
import PlanarHom.HomogeneousSourceOrientationFullAxiomAudit
import PlanarHom.HomogeneousSourceOrientationFullRegressions
import PlanarHom.HomogeneousSourceOrientationReduction
import PlanarHom.TypedHomogeneousSourceAccess

-- Genuine fixed network FP, literal gadget support and verified collar/clipping sources.
import PlanarHom.ColoredEdgeGadgetJointReduction
import PlanarHom.ColoredGadgetReindex
import PlanarHom.ColoredSignatureFieldMap
import PlanarHom.ContextualColoredMatrix
import PlanarHom.EdgeGadgetTemplateGeometry
import PlanarHom.FixedGadgetNetworkAxiomAudit
import PlanarHom.FixedGadgetNetworkBounds
import PlanarHom.FixedGadgetNetworkCode
import PlanarHom.FixedGadgetNetworkCompiler
import PlanarHom.FixedGadgetNetworkMachines
import PlanarHom.FixedGadgetNetworkRegressions
import PlanarHom.FktClippingAxiomAudit
import PlanarHom.FktClippingRegressions
import PlanarHom.GadgetSemanticAxiomAudit
import PlanarHom.GadgetSemanticRegressions
import PlanarHom.OccurrenceKasteleynCircleClippingBridge
import PlanarHom.OccurrenceKasteleynEdgeCollars
import PlanarHom.OccurrenceKasteleynOriginalCollarBridge
import PlanarHom.PlanarHeterogeneousGadgetInsertion
import PlanarHom.PlanarityLRRealizationGermPieces
import PlanarHom.PolygonalOppositeStripSeparation
import PlanarHom.PolygonalSignedStripWidths
import PlanarHom.RadialPottsAssemblyCircleCoordinates
import PlanarHom.RadialPottsAssemblyCircleMap
import PlanarHom.RadialPottsAssemblyRibbonCircleClip
import PlanarHom.RadialPottsAssemblyRibbonGerms
import PlanarHom.TypedGadgetAppendColoredTemplates
import PlanarHom.TypedGadgetAppendRestrictedSemantics
import PlanarHom.TypedGadgetAppendTyping

-- Actual DFS source programs and semantic invariants, not complete planarity.
import PlanarHom.DepthFirstSearchAxiomAudit
import PlanarHom.DepthFirstSearchRegressions
import PlanarHom.PlanarityDepthFirstSearch
import PlanarHom.PlanarityDepthFirstSearchAncestors
import PlanarHom.PlanarityDepthFirstSearchCodecs
import PlanarHom.PlanarityDepthFirstSearchCoverage
import PlanarHom.PlanarityDepthFirstSearchMachines
import PlanarHom.PlanarityDepthFirstSearchNeighbours
import PlanarHom.PlanarityDepthFirstSearchProgram
import PlanarHom.PlanarityDepthFirstSearchRuntimeBounds
import PlanarHom.PlanarityDepthFirstSearchSources
import PlanarHom.PlanarityDepthFirstSearchStack
import PlanarHom.PlanarityDepthFirstSearchStepMachines
import PlanarHom.PlanarityDepthFirstSearchTermination
import PlanarHom.PlanarityDepthFirstSearchWordBounds

-- Exact numeric edge-substitution evaluation and actual decoded-raw machines.
import PlanarHom.EdgeSubstitutionAxiomAudit
import PlanarHom.EdgeSubstitutionCode
import PlanarHom.EdgeSubstitutionRawMachine
import PlanarHom.EdgeSubstitutionRegressions
import PlanarHom.EdgeSubstitutionSemantics
import PlanarHom.FixedGadgetNetworkSemantics

-- Complete actual typed gadget closure and proved LR/sorting primitives.
import PlanarHom.ContextNatSortCorrectness
import PlanarHom.ContextNatSortMachines
import PlanarHom.ContextSortAxiomAudit
import PlanarHom.ContextSortRegressions
import PlanarHom.EdgeGadgetNetworkReduction
import PlanarHom.EdgeSubstitutionAllocation
import PlanarHom.EdgeSubstitutionGeometry
import PlanarHom.EdgeSubstitutionGeometryAxiomAudit
import PlanarHom.EdgeSubstitutionGeometryRegressions
import PlanarHom.FullTypedGadgetAxiomAudit
import PlanarHom.PlanarityLRAlignment
import PlanarHom.PlanarityLRAlignmentSafety
import PlanarHom.PlanarityLRConstraintBlocks
import PlanarHom.PlanarityLRConstraintMachines
import PlanarHom.PlanarityLRConstraints
import PlanarHom.PlanarityLRForestFacts
import PlanarHom.PlanarityLRNesting
import PlanarHom.PlanarityLRNestingMachines
import PlanarHom.PlanarityLRPrimitiveMachines
import PlanarHom.PlanarityLRRawConstraints
import PlanarHom.PlanarityLRReturnFacts
import PlanarHom.PlanarityLRReturnMachines
import PlanarHom.PlanarityLRRotationRowMachines
import PlanarHom.PlanarityParityMachines
import PlanarHom.PlanarityParityMaterialized
import PlanarHom.PlanarityParityPolynomial
import PlanarHom.PlanarityParitySolver
import PlanarHom.RawLRAxiomAudit
import PlanarHom.RawLRRegressions
import PlanarHom.TypedContextualGadgetClosure
import PlanarHom.TypedContextualGadgetFieldMap
import PlanarHom.TypedContextualGadgetReduction
import PlanarHom.TypedContextualGadgetReductionX
import PlanarHom.TypedContextualGadgetSemantics
import PlanarHom.TypedGadgetAppend
import PlanarHom.TypedGadgetAppendColoredReduction
import PlanarHom.TypedGadgetAppendColoredRegressions
import PlanarHom.TypedGadgetAppendColoredTyping
import PlanarHom.TypedGadgetAppendCompiler
import PlanarHom.TypedGadgetAppendMachines
import PlanarHom.TypedGadgetAppendReduction
import PlanarHom.TypedGadgetAppendRegressions
import PlanarHom.TypedGadgetAppendTransport
import PlanarHom.TypedMixedPhysicalAvailabilityOperation

-- Actual ordinary-input direct rotation/face-step runtime; geometric extraction remains open.
import PlanarHom.DirectRotationAxiomAudit
import PlanarHom.DirectRotationRegressions
import PlanarHom.DynamicListIndexMachines
import PlanarHom.NatWordComparisonMachines
import PlanarHom.PlanarityLRBranchPaths
import PlanarHom.PlanarityLRDirect
import PlanarHom.PlanarityLRDirectMachines
import PlanarHom.PlanarityLREventMachines
import PlanarHom.PlanarityLREventOrder
import PlanarHom.PlanarityRotationCode
import PlanarHom.PlanarityRotationCodeMachines

-- Exact physical mixed gadgets and full recovered consumers; typed rotation incidence.
import PlanarHom.FullMixedPhysicalConsumerAxiomAudit
import PlanarHom.FullMixedPhysicalConsumerRegressions
import PlanarHom.PlanarityLRAlignedRegressions
import PlanarHom.PlanarityLRBlockRegressions
import PlanarHom.PlanarityLRRawRegressions
import PlanarHom.PlanarityLRRealizationRotationSystem
import PlanarHom.PlanarityLRRotationAxiomAudit
import PlanarHom.PlanarityLRRotationRegressions
import PlanarHom.PlanarityLRRowIncidence
import PlanarHom.PlanarityLRStructureRegressions
import PlanarHom.PlanarityLRTreeInsertion
import PlanarHom.PlanarityParityRegressions
import PlanarHom.RecoveredMixedDefinitionCompatibility
import PlanarHom.RectangularDoubleDiamondGeometry
import PlanarHom.RectangularDoubleDiamondGraph
import PlanarHom.RectangularDoubleDiamondSemantics
import PlanarHom.RectangularMixedBlockCoordinates
import PlanarHom.RectangularMixedFormsAxiomAudit
import PlanarHom.RectangularMixedFormsRegressions
import PlanarHom.RectangularMixedGram
import PlanarHom.RectangularMixedPhysicalForms
import PlanarHom.TypedMixedPhysicalAvailability
import PlanarHom.TypedMixedPhysicalAvailabilityAxiomAudit
import PlanarHom.TypedMixedPhysicalAvailabilityGram
import PlanarHom.TypedMixedPhysicalAvailabilityRegressions
import PlanarHom.TypedMixedPhysicalAvailabilitySemantics
import PlanarHom.TypedMixedPhysicalAvailabilityTransport
import PlanarHom.TypedMixedPhysicalAvailabilityValues

-- Actual Potts source program, explicitly conditional common cube, and raw face/contour bridges.
import PlanarHom.AvailableClosedFamilyCube
import PlanarHom.CliqueSizePolynomials
import PlanarHom.CliqueSizeProductIdentities
import PlanarHom.CommonCubeChartBasicConsequences
import PlanarHom.CommonCubeChartDefinition
import PlanarHom.CommonCubeConditionalAxiomAudit
import PlanarHom.CommonCubeConditionalRegressions
import PlanarHom.DynamicParameterizedGraphReduction
import PlanarHom.EmbeddedSegmentTree
import PlanarHom.EmbeddedSegmentTreeAttachment
import PlanarHom.EmbeddedSegmentTreeCollapse
import PlanarHom.FaceDualAxiomAudit
import PlanarHom.FaceDualRegressions
import PlanarHom.FaceRootsAxiomAudit
import PlanarHom.FaceRootsRegressions
import PlanarHom.FaceTablesAxiomAudit
import PlanarHom.FaceTablesRegressions
import PlanarHom.FiniteOrbitBoundary
import PlanarHom.FinitePermutationCut
import PlanarHom.HammingKernelSquares
import PlanarHom.HammingKernelTensor
import PlanarHom.HammingPottsFieldFamily
import PlanarHom.HammingPottsIsolationAxiomAudit
import PlanarHom.HammingPottsIsolationReduction
import PlanarHom.HammingPottsIsolationRegressions
import PlanarHom.HammingPottsProductIdentities
import PlanarHom.HammingPottsRecoveryReduction
import PlanarHom.HammingPottsRootRecovery
import PlanarHom.HammingPottsSourceAxiomAudit
import PlanarHom.HammingPottsSourceRegressions
import PlanarHom.HammingPottsTensorPartition
import PlanarHom.HammingPottsToSource
import PlanarHom.LRIntervalsAxiomAudit
import PlanarHom.LRIntervalsRegressions
import PlanarHom.LRWordsAxiomAudit
import PlanarHom.LRWordsRegressions
import PlanarHom.ListPrefixMachines
import PlanarHom.NatWordPrefixConvexity
import PlanarHom.PlanarProperLocalizedCollapse
import PlanarHom.PlanarRootedTreeExtraction
import PlanarHom.PlanarSegmentComplementHomeomorph
import PlanarHom.PlanarityFaceCache
import PlanarHom.PlanarityFaceCodeMachines
import PlanarHom.PlanarityFaceCodeProgram
import PlanarHom.PlanarityFaceDualConnectivity
import PlanarHom.PlanarityFaceDualData
import PlanarHom.PlanarityFaceLabels
import PlanarHom.PlanarityFaceOrbitMachines
import PlanarHom.PlanarityFaceOrientationCorrectness
import PlanarHom.PlanarityFaceRootCache
import PlanarHom.PlanarityFaceRootMachines
import PlanarHom.PlanarityFaceRootProgram
import PlanarHom.PlanarityFaceRoots
import PlanarHom.PlanarityFaceStepBounds
import PlanarHom.PlanarityFaceTableMaterialization
import PlanarHom.PlanarityLRBackWords
import PlanarHom.PlanarityLRBranchEventOrder
import PlanarHom.PlanarityLRComponents
import PlanarHom.PlanarityLRContourAxiomAudit
import PlanarHom.PlanarityLRContourCycles
import PlanarHom.PlanarityLRContourCyclesAxiomAudit
import PlanarHom.PlanarityLRContourPermutation
import PlanarHom.PlanarityLRDartConnectivity
import PlanarHom.PlanarityLRDrawnTree
import PlanarHom.PlanarityLRDrawnTreeAxiomAudit
import PlanarHom.PlanarityLRDualReachability
import PlanarHom.PlanarityLRFaceAxiomAudit
import PlanarHom.PlanarityLRFaceBoundary
import PlanarHom.PlanarityLRFaceComponents
import PlanarHom.PlanarityLRFacePermutation
import PlanarHom.PlanarityLRFaceRegressions
import PlanarHom.PlanarityLRFaceRepresentatives
import PlanarHom.PlanarityLRNoninterleavingIntervals
import PlanarHom.PlanarityLROutgoingOrder
import PlanarHom.PlanarityLRRealizationArches
import PlanarHom.PlanarityLRRoutingAxiomAudit
import PlanarHom.PlanarityLRRoutingRegressions
import PlanarHom.PlanarityLRSubtreeIntervals
import PlanarHom.PlanarityLRTreeCuts
import PlanarHom.PlanarityLRTreeWords
import PlanarHom.PlanarityLRWordPaths
import PlanarHom.PlanarityLRWordSubtrees
import PlanarHom.PositivePottsInterface
import PlanarHom.PromisedSharpPHardness
import PlanarHom.ProperPlaneCollapse
import PlanarHom.RadialPottsAssemblyCircleArches
import PlanarHom.RectangularCoreSourceCoordinates
import PlanarHom.RectangularCoreSourceEntranceConditional
import PlanarHom.TypedHomogeneousCommonCharts
import PlanarHom.TypedSideCommonChartSeed
import PlanarHom.UniformSquaredDistanceKernel
import PlanarHom.BooleanTensorDichotomy

import PlanarHom.MainDichotomiesClosed

import PlanarHom.BodyAcceptanceAggregate

import PlanarHom.RemainingBodyAcceptanceAggregate

import PlanarHom.AppendixFirstAcceptanceAggregate

import PlanarHom.FinalWeightedAcceptanceAggregate
