import Mathlib.Data.Fintype.BigOperators
import Mathlib.Data.Fintype.Pi
import Mathlib.Data.List.OfFn
import Mathlib.Algebra.BigOperators.Ring.Finset

/-!
# Counting certificates generated by prepending bits

The binary generator recursively prepends its choices to an accumulator. Its
leaf count agrees with the number of accepted fixed-length words, even though
the generation order reverses the order in which those words are read.
-/

namespace PlanarHom.CertificateWordCount

/-- Count accepted leaves after prepending `n` binary choices to an accumulator. -/
def bitsWordCount (V : List Bool → Bool) : ℕ → List Bool → ℕ
  | 0, acc => if V acc = true then 1 else 0
  | n + 1, acc => bitsWordCount V n (false :: acc) + bitsWordCount V n (true :: acc)

@[simp] theorem bitsWordCount_zero (V : List Bool → Bool) (acc : List Bool) :
    bitsWordCount V 0 acc = if V acc = true then 1 else 0 := rfl

@[simp] theorem bitsWordCount_succ (V : List Bool → Bool) (n : ℕ) (acc : List Bool) :
    bitsWordCount V (n + 1) acc =
      bitsWordCount V n (false :: acc) + bitsWordCount V n (true :: acc) := rfl

/-- Split a sum over binary words according to the first bit. -/
theorem sum_binaryWords {n : ℕ} (f : (Fin (n + 1) → Bool) → ℕ) :
    (∑ w, f w) = (∑ w : Fin n → Bool, f (Fin.cons false w)) +
      (∑ w : Fin n → Bool, f (Fin.cons true w)) := by
  rw [← (Fin.consEquiv (fun _ : Fin (n + 1) => Bool)).sum_comp f]
  rw [Fintype.sum_prod_type]
  simp [Fin.consEquiv, Nat.add_comm]

/-- Prepending the generated bits reverses the transition word. -/
theorem bitsWordCount_eq_sum_reverse (V : List Bool → Bool) (n : ℕ) (acc : List Bool) :
    bitsWordCount V n acc =
      ∑ w : Fin n → Bool,
        if V ((List.ofFn w).reverse ++ acc) = true then 1 else 0 := by
  induction n generalizing acc with
  | zero => simp [bitsWordCount]
  | succ n ih =>
      rw [bitsWordCount_succ, sum_binaryWords, ih, ih]
      simp only [List.ofFn_cons, List.reverse_cons, List.append_assoc,
        List.singleton_append]

/-- Reverse the indices of a binary word. -/
def reverseWordEquiv (n : ℕ) : (Fin n → Bool) ≃ (Fin n → Bool) where
  toFun w i := w i.rev
  invFun w i := w i.rev
  left_inv w := by funext i; simp
  right_inv w := by funext i; simp

@[simp] theorem ofFn_reverseWordEquiv {n : ℕ} (w : Fin n → Bool) :
    List.ofFn (reverseWordEquiv n w) = (List.ofFn w).reverse := by
  apply List.ext_getElem (by simp)
  intro i hi hi'
  simp only [List.getElem_ofFn, List.getElem_reverse, List.length_ofFn, reverseWordEquiv,
    Equiv.coe_fn_mk]
  congr 1
  apply Fin.ext
  simp only [Fin.val_rev, Nat.sub_sub, Nat.add_comm]

/-- Reversal merely permutes the words in any sum. -/
theorem sum_reverseWords (n : ℕ) (f : List Bool → ℕ) :
    (∑ w : Fin n → Bool, f (List.ofFn w).reverse) =
      ∑ w : Fin n → Bool, f (List.ofFn w) := by
  simpa only [ofFn_reverseWordEquiv] using
    (reverseWordEquiv n).sum_comp (fun w => f (List.ofFn w))

/-- With an empty accumulator, the generator counts ordinary fixed-length words. -/
theorem bitsWordCount_eq_sum (V : List Bool → Bool) (n : ℕ) :
    bitsWordCount V n [] =
      ∑ w : Fin n → Bool, if V (List.ofFn w) = true then 1 else 0 := by
  rw [bitsWordCount_eq_sum_reverse]
  simp only [List.append_nil]
  exact sum_reverseWords n (fun xs => if V xs = true then 1 else 0)

/-- The number of accepting leaves is the cardinality of accepted certificates. -/
theorem bitsWordCount_eq_card (V : List Bool → Bool) (n : ℕ) :
    bitsWordCount V n [] =
      Fintype.card {w : Fin n → Bool // V (List.ofFn w) = true} := by
  rw [bitsWordCount_eq_sum, Fintype.card_subtype]
  exact Finset.sum_boole _ _

end PlanarHom.CertificateWordCount
