import PlanarHom.ColoringMacroCrossFramedFaceTableNext
import PlanarHom.ColoringMacroCrossFramedFaceTablePrev
import PlanarHom.ColoringMacroCrossFramedFaceTableLabel
import PlanarHom.ColoringMacroCrossFramedFaceTableRoot
import PlanarHom.ColoringMacroCrossFramedFaceTableRank
import PlanarHom.ColoringMacroCrossFramedFaceTableGap
