import PlanarHom.ProperPlaneCollapse

/-!
# NEW finite embedded segment trees

This is ordinary geometric incidence data generated by leaf insertion. The
construction does not assume a chart, rotation, Jordan separation, or collapse.
-/
noncomputable section
open Set
open scoped Convex
namespace PlanarHom.MultiGraph
local instance : DecidableEq Plane := Classical.decEq _

/-- Literal vertices and closed geometric pieces, including the initial root. -/
def segmentTreeSupport (V : Finset Plane) (E : Finset (Plane×Plane)) : Set Plane :=
  (V : Set Plane) ∪ ⋃ e∈E, [e.1 -[ℝ] e.2]

/-- Build a finite geometric tree by adding one new leaf piece at an existing
vertex. The only geometric premise is actual intersection at that attachment. -/
inductive EmbeddedSegmentTree (r : Plane) : Finset Plane → Finset (Plane×Plane) → Prop
  | root : EmbeddedSegmentTree r {r} ∅
  | leaf {V E} (tree : EmbeddedSegmentTree r V E) (a b : Plane)
      (hb : b∈V) (hab : a≠b)
      (contact : ∀ x, x∈[a -[ℝ] b] → x∈segmentTreeSupport V E → x=b) :
      EmbeddedSegmentTree r (insert a V) (insert (a,b) E)

namespace EmbeddedSegmentTree
variable {r : Plane} {V : Finset Plane} {E : Finset (Plane×Plane)}

theorem vertex_mem_support {v : Plane} (hv : v∈V) : v∈segmentTreeSupport V E := Or.inl hv

theorem piece_subset_support {e : Plane×Plane} (he : e∈E) :
    [e.1 -[ℝ] e.2] ⊆ segmentTreeSupport V E := by
  intro x hx
  exact Or.inr (Set.mem_iUnion.mpr ⟨e,Set.mem_iUnion.mpr ⟨he,hx⟩⟩)

theorem root_mem (T : EmbeddedSegmentTree r V E) : r∈V := by
  induction T with
  | root => simp
  | leaf T a b hb hab hc ih => exact Finset.mem_insert_of_mem ih

theorem endpoints_mem (T : EmbeddedSegmentTree r V E) {e : Plane×Plane} (he : e∈E) :
    e.1∈V ∧ e.2∈V := by
  induction T with
  | root => simp at he
  | @leaf V E T a b hb hab hc ih =>
      rcases Finset.mem_insert.mp he with rfl | he
      · exact ⟨Finset.mem_insert_self _ _,Finset.mem_insert_of_mem hb⟩
      · have hh := ih he
        exact ⟨Finset.mem_insert_of_mem hh.1,Finset.mem_insert_of_mem hh.2⟩

/-- No old vertex hides inside an unrelated piece. This is derived from the
leaf construction and is the exact incidence fact needed for radial preservation. -/
theorem vertex_piece_contact (T : EmbeddedSegmentTree r V E)
    {v : Plane} (hv : v∈V) {e : Plane×Plane} (he : e∈E) (hseg : v∈[e.1 -[ℝ] e.2]) :
    v=e.1 ∨ v=e.2 := by
  induction T generalizing v e with
  | root => simp at he
  | @leaf V E T a b hb hab hc ih =>
      rcases Finset.mem_insert.mp he with henew | heold
      · have hseg' : v∈[a -[ℝ] b] := by simpa only [henew] using hseg
        rcases Finset.mem_insert.mp hv with hvnew | hvold
        · exact Or.inl (hvnew.trans (congrArg Prod.fst henew).symm)
        · exact Or.inr ((hc v hseg' (vertex_mem_support hvold)).trans (congrArg Prod.snd henew).symm)
      · rcases Finset.mem_insert.mp hv with hvnew | hvold
        · have haold : a∈segmentTreeSupport V E := hvnew ▸ piece_subset_support (V := V) heold hseg
          exact False.elim (hab (hc a (left_mem_segment ℝ a b) haold))
        · exact ih hvold heold hseg

theorem support_leaf (a b : Plane) (_hb : b∈V) :
    segmentTreeSupport (insert a V) (insert (a,b) E) =
      [a -[ℝ] b] ∪ segmentTreeSupport V E := by
  ext x
  simp only [segmentTreeSupport,Finset.coe_insert,Set.mem_union,Set.mem_insert_iff,
    Finset.mem_insert,Set.mem_iUnion]
  constructor
  · rintro ((rfl | hv) | ⟨e,(rfl | he),hseg⟩)
    · exact Or.inl (left_mem_segment ℝ x b)
    · exact Or.inr (Or.inl hv)
    · exact Or.inl hseg
    · exact Or.inr (Or.inr ⟨e,he,hseg⟩)
  · rintro (hseg | hv | ⟨e,he,hseg⟩)
    · exact Or.inr ⟨(a,b),Or.inl rfl,hseg⟩
    · exact Or.inl (Or.inr hv)
    · exact Or.inr ⟨e,Or.inr he,hseg⟩

theorem isCompact_support (V : Finset Plane) (E : Finset (Plane×Plane)) :
    IsCompact (segmentTreeSupport V E) := by
  apply (Finset.finite_toSet V).isCompact.union
  apply (Finset.finite_toSet E).isCompact_biUnion
  intro e _
  rw [segment_eq_image_lineMap]
  exact isCompact_Icc.image (by fun_prop)

end EmbeddedSegmentTree
end PlanarHom.MultiGraph
