import Mathlib.FieldTheory.IntermediateField.Adjoin.Basic
import Mathlib.LinearAlgebra.FiniteDimensional.Defs

/-!
# A common fixed rational field for every finite algebraic language

The field and basis are fixed problem data. This establishes their existence,
not a uniform algorithm constructing a field presentation from variable algebraic
input. No compositum of an input-dependent collection of sample fields is used.
-/

noncomputable section
namespace PlanarHom.FixedAlgebraicField

variable {L ι : Type} [Field L] [Algebra ℚ L] [Fintype ι]

/-- The actual intermediate field generated by the fixed alphabet. -/
def commonField (A : ι → L) : IntermediateField ℚ L := IntermediateField.adjoin ℚ (Set.range A)

omit [Fintype ι] in
theorem mem_commonField (A : ι → L) (i : ι) : A i ∈ commonField A :=
  IntermediateField.subset_adjoin ℚ (Set.range A) (Set.mem_range_self i)

/-- A finite alphabet of algebraic constants lies in a finite-dimensional common field. -/
theorem commonField_finiteDimensional (A : ι → L) (hA : ∀ i, IsAlgebraic ℚ (A i)) :
    FiniteDimensional ℚ (commonField A) := by
  apply IntermediateField.finiteDimensional_adjoin
  rintro x ⟨i, rfl⟩
  exact (hA i).isIntegral

/-- The chosen finite rational basis used by the exact field codec and circuits. -/
def commonBasis (A : ι → L) (hA : ∀ i, IsAlgebraic ℚ (A i)) :
    Module.Basis (Fin (Module.finrank ℚ (commonField A))) ℚ (commonField A) := by
  letI := commonField_finiteDimensional A hA
  exact Module.finBasis ℚ (commonField A)

/-- The fixed alphabet is represented by genuine elements of the common field. -/
def liftAlphabet (A : ι → L) (i : ι) : commonField A := ⟨A i, mem_commonField A i⟩

@[simp] theorem liftAlphabet_coe (A : ι → L) (i : ι) : (liftAlphabet A i : L) = A i := rfl

end PlanarHom.FixedAlgebraicField
