import PlanarHom.PottsComponentRank
import PlanarHom.GraphComponentSemantics

/-!
# Agreement of quotient components with the executable component algorithm

The equivalence generated by all edge occurrences agrees with support-path
reachability. Its quotient is therefore in bijection with the nonempty parts
returned by the component algorithm, including isolated vertices.
-/
noncomputable section
open Classical

namespace PlanarHom.GraphComponentCode
open Complexity

/-- A support path induces equality in the occurrence-generated component quotient. -/
theorem componentSetoid_univ_of_reach {b u : ℕ} (g : MixedCode) (hg : g.Valid b u)
    {v w : ℕ} (hv : v < g.vertices) (hw : w < g.vertices) (h : Reach g.edges v w) :
    (g.toMultiGraph hg).componentSetoid Finset.univ ⟨v, hv⟩ ⟨w, hw⟩ := by
  induction h with
  | refl => exact Relation.EqvGen.refl _
  | @tail v w hpath hadj ih =>
    have hmid := (adjacent_vertices_lt g hg hadj).1
    apply Relation.EqvGen.trans _ _ _ (ih hmid)
    obtain ⟨_,e,he,h|h⟩ := hadj
    · obtain ⟨i,rfl⟩ := List.mem_iff_get.mp he
      exact Relation.EqvGen.rel _ _ ⟨i, Finset.mem_univ i, Fin.ext h.1, Fin.ext h.2⟩
    · obtain ⟨i,rfl⟩ := List.mem_iff_get.mp he
      exact Relation.EqvGen.symm _ _
        (Relation.EqvGen.rel _ _ ⟨i, Finset.mem_univ i, Fin.ext h.1, Fin.ext h.2⟩)

/-- Quotient components and support-path connectivity describe the same relation. -/
theorem componentSetoid_univ_iff_reach {b u : ℕ} (g : MixedCode) (hg : g.Valid b u)
    (v w : Fin g.vertices) :
    (g.toMultiGraph hg).componentSetoid Finset.univ v w ↔ Reach g.edges v.val w.val := by
  constructor
  · intro h
    induction h with
    | rel v w h =>
      obtain ⟨e,_,rfl,rfl⟩ := h
      exact edge_reach g.edges (g.edges.get e) (List.get_mem _ _)
    | refl => exact Relation.ReflTransGen.refl
    | symm v w h ih => exact reach_symm g.edges ih
    | trans v w z h₁ h₂ ih₁ ih₂ => exact ih₁.trans ih₂
  · exact componentSetoid_univ_of_reach g hg v.isLt w.isLt

/-- The computed parts count is exactly the mathematical component count. -/
theorem componentCount_eq_parts_length {b u : ℕ} (g : MixedCode) (hg : g.Valid b u) :
    (g.toMultiGraph hg).componentCount Finset.univ = (parts g).length := by
  let owner : Fin g.vertices → PartIndex g :=
    fun v => Classical.choose (vertex_unique_part g v.val v.isLt)
  have howner (v : Fin g.vertices) : v.val ∈ (parts g).get (owner v) :=
    (Classical.choose_spec (vertex_unique_part g v.val v.isLt)).1
  have howner_eq (v : Fin g.vertices) (p : PartIndex g)
      (hp : v.val ∈ (parts g).get p) : owner v = p :=
    ((Classical.choose_spec (vertex_unique_part g v.val v.isLt)).2 p hp).symm
  have he : (g.toMultiGraph hg).EdgeConstant Finset.univ owner := by
    intro e _
    obtain ⟨p,hp,_⟩ := edge_unique_part g hg (g.edges.get e) (List.get_mem _ _)
    rw [howner_eq _ p hp.1, howner_eq _ p hp.2]
  let f : (g.toMultiGraph hg).Components Finset.univ → PartIndex g :=
    Quotient.lift owner (fun _ _ h => (g.toMultiGraph hg).edgeConstant_respects _ _ he h)
  have hf : Function.Bijective f := by
    constructor
    · intro c d
      induction c using Quotient.inductionOn with
      | h v =>
        induction d using Quotient.inductionOn with
        | h w =>
          intro hvw
          apply Quotient.sound
          apply (componentSetoid_univ_iff_reach g hg v w).mpr
          apply together_reach g
          refine ⟨(parts g).get (owner v), List.get_mem _ _, howner v, ?_⟩
          change owner v = owner w at hvw
          rw [hvw]
          exact howner w
    · intro p
      obtain ⟨v,hv⟩ := List.exists_mem_of_ne_nil _
        (parts_nonempty g _ (List.get_mem _ p))
      let w : Fin g.vertices := ⟨v, part_vertex_lt g _ (List.get_mem _ p) v hv⟩
      exact ⟨Quotient.mk _ w, howner_eq w p hv⟩
  simpa only [MultiGraph.componentCount, PartIndex, Fintype.card_fin] using
    Fintype.card_of_bijective hf

/-- The executable list of extracted connected instances has the same count. -/
theorem componentCount_eq_components_length {b u : ℕ} (g : MixedCode)
    (hg : g.Valid b u) :
    (g.toMultiGraph hg).componentCount Finset.univ = (components g).length := by
  simpa [components] using componentCount_eq_parts_length g hg

end PlanarHom.GraphComponentCode
