import PlanarHom.Basic
import Mathlib.Data.Setoid.Basic
import Mathlib.Data.Fintype.Card
import Mathlib.Data.Fintype.Powerset

/-!
# The random-cluster expansion for occurrence-labelled multigraphs

An edge subset is a `Finset E`, so parallel occurrences remain independently
selectable. Components are the equivalence classes generated by the endpoints
of selected occurrences. In particular all original vertices, including isolates,
are present, and a loop imposes only a reflexive equation.
-/
noncomputable section
open scoped BigOperators
open Classical

namespace PlanarHom.MultiGraph
variable {V E C R : Type*}

/-- Endpoint pairs of selected edge occurrences. -/
def selectedPair (G : MultiGraph V E) (A : Finset E) (u v : V) : Prop :=
  ∃ e ∈ A, G.src e = u ∧ G.dst e = v

/-- Finite-path undirected connectivity generated by selected occurrences. -/
def componentSetoid (G : MultiGraph V E) (A : Finset E) : Setoid V :=
  Relation.EqvGen.setoid (G.selectedPair A)

/-- Components of the spanning subgraph, with all original vertices retained. -/
abbrev Components (G : MultiGraph V E) (A : Finset E) := Quotient (G.componentSetoid A)

instance componentsFintype [Fintype V] (G : MultiGraph V E) (A : Finset E) :
    Fintype (G.Components A) := Fintype.ofFinite _

def componentCount [Fintype V] (G : MultiGraph V E) (A : Finset E) : ℕ :=
  Fintype.card (G.Components A)

/-- Color assignments constant on every selected edge. -/
def EdgeConstant (G : MultiGraph V E) (A : Finset E) (σ : V → C) : Prop :=
  ∀ e ∈ A, σ (G.src e) = σ (G.dst e)

theorem edgeConstant_respects (G : MultiGraph V E) (A : Finset E) (σ : V → C)
    (hσ : G.EdgeConstant A σ) {u v : V} (h : G.componentSetoid A u v) : σ u = σ v := by
  induction h with
  | rel u v h =>
    obtain ⟨e, he, rfl, rfl⟩ := h
    exact hσ e he
  | refl => rfl
  | symm u v h ih => exact ih.symm
  | trans u v w h₁ h₂ ih₁ ih₂ => exact ih₁.trans ih₂

/-- Exact correspondence between edge-constant colorings and one color per
actual connected component. It also covers an empty color type. -/
def componentColoringEquiv (G : MultiGraph V E) (A : Finset E) (C : Type*) :
    {σ : V → C // G.EdgeConstant A σ} ≃ (G.Components A → C) where
  toFun σ := Quotient.lift σ.1 (fun _ _ h => G.edgeConstant_respects A σ.1 σ.2 h)
  invFun τ := ⟨fun v => τ (Quotient.mk _ v), fun e he => congrArg τ
    (Quotient.sound (Relation.EqvGen.rel _ _ ⟨e, he, rfl, rfl⟩))⟩
  left_inv σ := by rfl
  right_inv τ := by
    funext x
    induction x using Quotient.inductionOn with
    | h v => rfl

theorem card_edgeConstant [Fintype V] [Fintype C] (G : MultiGraph V E) (A : Finset E) :
    Fintype.card {σ : V → C // G.EdgeConstant A σ} =
      Fintype.card C ^ G.componentCount A := by
  rw [Fintype.card_congr (G.componentColoringEquiv A C), Fintype.card_fun]
  rfl

/-- The Potts interaction with diagonal 2 and off-diagonal 1, written in a
form valid over any commutative semiring. -/
def pottsInteraction [CommSemiring R] (i j : C) : R := (if i = j then 1 else 0) + 1

theorem pottsInteraction_eq [Fintype C] [CommSemiring R] :
    (pottsInteraction : Matrix C C R) = 1 + Matrix.of (fun _ _ => 1) := by
  ext i j
  change (if i = j then (1 : R) else 0) + 1 = (1 : Matrix C C R) i j + 1
  rw [Matrix.one_apply]

theorem edgeIndicator_prod [CommSemiring R] (G : MultiGraph V E) (A : Finset E)
    (σ : V → C) :
    (∏ e ∈ A, (if σ (G.src e) = σ (G.dst e) then (1 : R) else 0)) =
      if G.EdgeConstant A σ then 1 else 0 := by
  by_cases h : G.EdgeConstant A σ
  · rw [if_pos h]
    apply Finset.prod_eq_one
    intro e he
    simp [h e he]
  · have he : ∃ e ∈ A, σ (G.src e) ≠ σ (G.dst e) := by
      simpa [EdgeConstant] using h
    obtain ⟨e, he, hne⟩ := he
    rw [if_neg h]
    apply Finset.prod_eq_zero he
    simp [hne]

theorem sum_edgeIndicator [Fintype V] [Fintype C] [CommSemiring R]
    (G : MultiGraph V E) (A : Finset E) :
    (∑ σ : V → C, ∏ e ∈ A,
      (if σ (G.src e) = σ (G.dst e) then (1 : R) else 0)) =
      (Fintype.card C : R) ^ G.componentCount A := by
  simp_rw [G.edgeIndicator_prod]
  rw [Finset.sum_boole]
  have hc := G.card_edgeConstant (C := C) A
  rw [Fintype.card_subtype] at hc
  rw [hc, Nat.cast_pow]

/-- Fortuin–Kasteleyn expansion for the literal I+J interaction, over all
subsets of edge occurrences. There is no positivity or nonempty-color premise. -/
theorem potts_randomCluster [Fintype V] [Fintype E] [Fintype C] [CommSemiring R]
    (G : MultiGraph V E) :
    G.partition (pottsInteraction : Matrix C C R) (fun _ => 1) =
      ∑ A : Finset E, (Fintype.card C : R) ^ G.componentCount A := by
  simp only [partition, assignmentWeight_one, pottsInteraction]
  simp_rw [Finset.prod_add_one]
  rw [Finset.sum_comm]
  simp_rw [G.sum_edgeIndicator]
  simp

theorem componentCount_antitone [Fintype V] (G : MultiGraph V E)
    {A B : Finset E} (hAB : A ⊆ B) : G.componentCount B ≤ G.componentCount A := by
  let f : G.Components A → G.Components B := Quotient.map id (fun _ _ h =>
    Relation.EqvGen.mono (fun _ _ ⟨e, he, hu, hv⟩ => ⟨e, hAB he, hu, hv⟩) h)
  apply Fintype.card_le_of_surjective f
  intro x
  induction x using Quotient.inductionOn with
  | h v => exact ⟨Quotient.mk _ v, rfl⟩

theorem componentCount_le_vertices [Fintype V] (G : MultiGraph V E) (A : Finset E) :
    G.componentCount A ≤ Fintype.card V :=
  Fintype.card_le_of_surjective (fun v => (Quotient.mk _ v : G.Components A))
    Quotient.mk_surjective

end PlanarHom.MultiGraph
